[package]
name = "fuel_consumption"
version = "0.1.0"
authors = ["Tim Grossmann <contact.timgrossmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
